# Generated by Django 4.2.18 on 2025-03-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_is_active_user_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="payment_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
