# Generated by Django 4.2.2 on 2023-12-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("expenses", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("comments", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "leave",
                    models.IntegerField(default=0, help_text="Paid leave needed."),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="EventExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="events.event"
                    ),
                ),
                (
                    "expense",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="expenses.expense",
                    ),
                ),
            ],
        ),
    ]
